/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PedDetect */

#ifndef _Included_PedDetect
#define _Included_PedDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PedDetect
 * Method:    Initialization
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PedDetect_Initialization
        (JNIEnv *, jobject);

/*
 * Class:     PedDetect
 * Method:    Start_Detect
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_bn_ex7f_PedDetect_Start_1Detect
        (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
